### ISSUE TITLE
add nvm-windows

### ISSUE THREAD

**Issue by bcoe** [bcoe/awesome-cross-platform-nodejs#13]
I'd like to try out nvm-windows, and add it to this list:

https://github.com/coreybutler/nvm-windows?utm_source=nodeweekly&utm_medium=email

CC: @coreybutler

**Comment by coreybutler** [comment]
Thanks for adding... just a quick note on the "cross-platform" aspect of this: At the moment, nvm-windows is only on Windows. I have a version working on my Mac too, but it's not in a releasable state yet.

**Comment by bcoe** [comment]
@coreybutler with `awesome-cross-platform-node`, I'm mainly trying to point folks at great tools for developing on Windows, who are probably coming from an OSX or Linux background.

Great work with `nvm-windows`, I'm using this with my ievm now 👍

**Comment by coreybutler** [comment]
@bcoe - gotcha, and thanks! I'm glad to hear it's working out on ievm. If you have requests for anything new/different, don't hesitate to ping me. I'm laying out/working on the 2.0.0 roadmap now.
