### ISSUE TITLE
add section that provides links to known cross-platform issues

### ISSUE THREAD

**Issue by bcoe** [bcoe/awesome-cross-platform-nodejs#2]
it might be smart to add a section that links to write-ups on known cross-platform problems.

Thanks for the suggestion @jamestalmage.

**Comment by sindresorhus** [comment]
Some from the top of my head:

- https://github.com/nodejs/node-v0.x-archive/issues/2318 (`win-spawn` and `execa` in the list fixes this)
- Windows cmd.exe not supporting Unicode (hence the `figures` module in the list)
- Process exit flush issue on Node.js 0.10 on Windows. (@jamestalmage can expand on this)
- Native Node.js addons are very painful for Windows users.

**Comment by bcoe** [comment]
a start to this section landed in #5.
