### ISSUE TITLE
The link of "Node.js AppVeyor Configuration" is broken

### ISSUE THREAD

**Issue by Frederick-S** [bcoe/awesome-cross-platform-nodejs#20]
Hi, appveyor.yml was removed from that repo.

**Comment by ehmicky** [comment]
Thanks for letting us know, this is now fixed!

**Comment by ehmicky** [comment]
I've added you as a contributor for this helpful fix.

**Comment by Frederick-S** [comment]
> I've added you as a contributor for this helpful fix.

Wow, it's a great honor for me.
