### ISSUE TITLE
Add `MacOS` in the repository description

### ISSUE THREAD

**Issue by ehmicky** [bcoe/awesome-cross-platform-nodejs#23]
The current repository description is: `A curated list of awesome developer tools and libraries for writing and testing code that runs on Windows and Linux.`

While most cross-platform issues are Unix vs Windows, there are still few that are Mac-specific, e.g. when it comes to file watching or signals. 

Also probably Node.js should be mentioned as well.

Alternatives descriptions could be:
  - `A curated list of awesome developer tools and libraries for writing and testing Node.js code that runs on Windows, MacOS and Linux.`
  - `A curated list of awesome developer tools and libraries for writing and testing cross-platform Node.js code.`

**Comment by ehmicky** [comment]
I cannot modify the project's description, so this one would need to be done by @bcoe.

Also, I think a more concise description might be more catchy, such as: `A curated list of awesome developer tools for writing cross-platform Node.js code.`. That's quite subjective though :)

**Comment by bcoe** [comment]
@ehmicky I'm happy with: 

`A curated list of awesome developer tools for writing cross-platform Node.js code.`

If no one else has feedback?
