### ISSUE TITLE
Add `awesome` and `awesome-list` as GitHub topics

### ISSUE THREAD

**Issue by ehmicky** [bcoe/awesome-cross-platform-nodejs#27]
This is a [requirement to submit](https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md#requirements-for-your-awesome-list) on @sindresorhus `awesome` repository.

I am submitting an issue because I cannot edit GitHub topics myself.

**Comment by ehmicky** [comment]
@bcoe What do you think?

**Comment by bcoe** [comment]
I have added an `awesome`, and `awesome-list` topic 👌 , sorry for the slow reply.
