### ISSUE TITLE
Add Scope section to PR template.

### ISSUE THREAD

**Issue by ehmicky** [bcoe/awesome-cross-platform-nodejs#42]
Should we be explicit about the scope of this repository? 

I suggest we add few checkboxes in the PR template such as:
  - [ ] if you're adding a link, this should be related to cross-platform issues, i.e. OS-specific behavior. Also, those issues should not be solved in core Node.js.

This would discourage PRs about libraries that are cross-platform simply because they are built on top of Node.js which is (mostly) cross-platform.

Adding too many links not related to solving core Node.js cross-platform issues might also confuse readers like [those comments on Reddit](https://www.reddit.com/r/opensource/comments/bb8olx/tools_for_writing_crossplatform_nodejs/).

What do you think @bcoe? @sindresorhus?

**Comment by bcoe** [comment]
@ehmicky I'm for adding a point of clarification :+1: do you have the permissions necessary to do so?

**Comment by ehmicky** [comment]
Yes I can edit PR templates.

**Comment by ehmicky** [comment]
Fixed in https://github.com/bcoe/awesome-cross-platform-nodejs/commit/2e67a8b520bf01e100ef8d0e108869c8f74eb23c
