### ISSUE TITLE
Update Continuous integration section

### ISSUE THREAD

**Issue by CarlosZiegler** [bcoe/awesome-cross-platform-nodejs#52]
Hey people,
We can adding more tools in CI list:

- [ ] github-actions 
- [ ] gitlabCI

**Comment by ehmicky** [comment]
Hi @CarlosZiegler,
Right! Would you like to create a PR?

**Comment by CarlosZiegler** [comment]
Done #53

**Comment by ehmicky** [comment]
Thanks @CarlosZiegler !

**Comment by bcoe** [comment]
I think we can close this? let me know if I was mistaken.
