### ISSUE TITLE
Link to some of the basics:

### ISSUE THREAD

**Issue by jamestalmage** [bcoe/awesome-cross-platform-nodejs#6]
Most of the stuff offered here is pretty dense.

How about a few links that provide approachable but solid intros.

Here is one example that discusses paths: http://shapeshed.com/writing-cross-platform-node/

**Comment by bcoe** [comment]
@jamestalmage I like this, perhaps we can add it to the resources section?

**Comment by ehmicky** [comment]
I've added @jamestalmage as a contributor for this helpful resource.
